name: 构建

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
  push:
    tags:
      - v*

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install imageio
        
      - name: Set version
        id: set_version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            tag_name="${GITHUB_REF#refs/tags/}"
            echo "version=${tag_name:1}" >> $GITHUB_ENV
          else
            echo "version=0.0.1" >> $GITHUB_ENV
          fi

      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          mode: standalone
          script-name: main.py
          output-file: RandPicker
          enable-plugins: pyqt6
          include-data-files: |
            LICENSE=LICENSE
            default_config.json=default_config.json
            default_students.json=default_students.json
          include-data-dir: |
            ui=ui
            img=img
          include-module: conf
          disable-console: true
          windows-icon-from-ico: ./img/Logo.png
          file-version: ${{ env.version }}
          product-version: ${{ env.version }}
          product-name: RandPicker

      # - name: Package
      #   run: |
      #     curl -o zip.exe -L http://www.stahlworks.com/dev/zip.exe
      #     xcopy build\main.dist\* RandPicker\ /e/y
      #     ./zip -r -q RandPicker.zip RandPicker

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: RandPicker
          path: build/main.dist/**
          
