name: 构建

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build
        shell: pwsh
        run: |
          pyinstaller main.py ^
            --noconfirm --onedir ^
            --name RandPicker ^
            --content-directory . ^
            --add-data LICENSE:. ^
            --add-data conf:conf ^
            --add-data ui:ui ^
            --add-data img:img ^
            --add-data default_config.json:. ^
            --add-data default_students.json:. 


      # - name: Package
      #   run: |
      #     curl -o zip.exe -L http://www.stahlworks.com/dev/zip.exe
      #     xcopy build\main.dist\* RandPicker\ /e/y
      #     ./zip -r -q RandPicker.zip RandPicker

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: RandPicker
          path: dist/**